#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

TOPOEXEC_STRESS_PROFILE=soak \
TOPOEXEC_STRESS_DURATION_SECONDS="${TOPOEXEC_SOAK_LITE_DURATION_SECONDS:-2}" \
TOPOEXEC_STRESS_MAX_ITERATIONS="${TOPOEXEC_SOAK_LITE_MAX_ITERATIONS:-3}" \
TOPOEXEC_STRESS_SCALE="${TOPOEXEC_SOAK_LITE_SCALE:-16}" \
TOPOEXEC_STRESS_STEPS="${TOPOEXEC_SOAK_LITE_STEPS:-8}" \
TOPOEXEC_STRESS_TIMEOUT_SECONDS="${TOPOEXEC_SOAK_LITE_TIMEOUT_SECONDS:-30}" \
./scripts/stress_smoke.sh
